name: CI - React (TS) - Lint • Typecheck • Build • Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # LTS. Use 22.x if your project targets it.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        # If you don't have a package-lock.json yet, run `npm install` locally once and commit it

      - name: Lint (fail on warnings)
        run: npm run lint

      - name: Type-check (TS)
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

